### ISSUE TITLE
Is Delaunay triangulation not being used?

### ISSUE THREAD

**Issue by versatran01** [alexklwong/unsupervised-depth-completion-visual-inertial-odometry#1]
https://github.com/alexklwong/unsupervised-depth-completion-visual-inertial-odometry/blob/012554bdc4953011ba356d6520c66a291b540b33/src/data_utils.py#L201

It seems to be commented out in the source code.

**Comment by alexklwong** [comment]
Thank you for your interest!

By default LinearNDInterpolator already uses Delaunay Triangulation (from Qhull, http://www.qhull.org/)

Here's the reference:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.LinearNDInterpolator.html

Since we don't need the triangulation anywhere else, we commented out the line to pre-compute the triangulation (and left it there to remind ourselves that this is an option)

**Comment by versatran01** [comment]
I see, thanks.

**Comment by Li-goudan** [comment]
Sorry to bother you, but when I was training VOICED on the KITTI dataset, I encountered the following error and I didn't know how to solve it.

* python --version == 3.7.11
* tensorflow-gpu --version == 1.15.0

~~~python
Traceback (most recent call last):
  File "src/train_voiced.py", line 136, in <module>
    n_thread=args.n_thread)
  File "/home/udcvio/src/voiced_main.py", line 186, in train
    _, loss_value, summary = session.run([gradients, loss, model_summary])
  File "/root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [178,768,2], [batch]: [320,768,2]
         [[node dataloader/IteratorGetNext (defined at /root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[dataloader/IteratorGetNext/_15]]
  (1) Invalid argument: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [178,768,2], [batch]: [320,768,2]
         [[node dataloader/IteratorGetNext (defined at /root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'dataloader/IteratorGetNext':
  File "src/train_voiced.py", line 136, in <module>
    n_thread=args.n_thread)
  File "/home/udcvio/src/voiced_main.py", line 91, in train
    prefetch_size=2*n_thread)
  File "/home/udcvio/src/dataloader.py", line 73, in __init__
    self.next_element = self.iterator.get_next()
  File "/root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
    name=name)
  File "/root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2518, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/root/anaconda3/envs/udcvio/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
~~~
